data <- read.table("household_power_consumption.txt", header=TRUE, sep=";", stringsAsFactors=FALSE, dec=".")
dataset <- data[data$Date %in% c("1/2/2007","2/2/2007") ,]
#str(dataset)
datetime <- strptime(paste(dataset$Date, dataset$Time, sep=" "), "%d/%m/%Y %H:%M:%S") 
GlobalActivePower <- as.numeric(dataset$Global_active_power)
GlobalReactivePower <- as.numeric(dataset$Global_reactive_power)
Voltage <- as.numeric(dataset$Voltage)
SubMetering1 <- as.numeric(dataset$Sub_metering_1)
SubMetering2 <- as.numeric(dataset$Sub_metering_2)
SubMetering3 <- as.numeric(dataset$Sub_metering_3)
png("plot4.png", width=480, height=480)
par(mfrow = c(2, 2)) 
plot(datetime, GlobalActivePower, type="l", xlab="", ylab="Global Active Power", cex=0.2)
plot(datetime, Voltage, type="l", xlab="datetime", ylab="Voltage")
plot(datetime, SubMetering1, type="l", ylab="Energy sub metering", xlab="")
lines(datetime, SubMetering2, type="l", col="red")
lines(datetime, SubMetering3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lwd=3, cex=.75, col=c("black", "red", "blue"),bty="n")
plot(datetime, GlobalReactivePower, type="l", xlab="datetime", ylab="Global_reactive_power")
axis(2, at=seq(0.1, 0.5, by=0.1))
dev.off() 