data <- read.table("household_power_consumption.txt", header=TRUE, sep=";", stringsAsFactors=FALSE, dec=".")
dataset <- data[data$Date %in% c("1/2/2007","2/2/2007") ,]
#str(dataset)
datetime <- strptime(paste(dataset$Date, dataset$Time, sep=" "), "%d/%m/%Y %H:%M:%S") 
GlobalActivePower <- as.numeric(dataset$Global_active_power)
SubMetering1 <- as.numeric(dataset$Sub_metering_1)
SubMetering2 <- as.numeric(dataset$Sub_metering_2)
SubMetering3 <- as.numeric(dataset$Sub_metering_3)
png("plot3.png", width=480, height=480)
plot(datetime, SubMetering1, type="l", ylab="Energy sub metering", xlab="")
lines(datetime, SubMetering2, type="l", col="red")
lines(datetime, SubMetering3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1.5, lwd=3, col=c("black", "red", "blue"))
dev.off()